### ISSUE TITLE
put svg knob into svelte dj knob

### ISSUE THREAD

**Issue by neonfuz** [bismuthsoft/svelte-dj-knob#10]
- [x] Knob imported
- [x] Knob type selector

**Comment by neonfuz** [comment]
@44100hertz Is this necessary for 0.1? Feeling like kicking this to backburner while you're still making changes

**Comment by 44100hertz** [comment]
Moved.

**Comment by neonfuz** [comment]
@44100hertz I think I may wanna do this soon. What should I name the new knob?

**Comment by 44100hertz** [comment]
Elegant

**Comment by neonfuz** [comment]
PR: https://github.com/bismuthsoft/fazeoid/pull/82
