### ISSUE TITLE
Disallow non numeric input on knobs

### ISSUE THREAD

**Issue by neonfuz** [bismuthsoft/svelte-dj-knob#3]
thoughts: adding type="number" to the input disallows non numbers but also adds increment/decrement buttons which we don't want anyways. Casting the value to a number will stop breakage at least.

**Comment by 44100hertz** [comment]
IF you put it not a number it should at least reset it. Ideally non number typing should be totally ignored but I understand if that's not a thing.

**Comment by 44100hertz** [comment]
@neonfuz you need to publish the new version of svelte dj knob

**Comment by neonfuz** [comment]
@44100hertz updated

edit: updated both projects
